### ISSUE TITLE
如何进行label_processing

### ISSUE THREAD

**Issue by li-zemin** [TwistedW/label_processing#1]
您好，我在hwalsuklee 大神的代码issue中看到了你的提问：https://github.com/hwalsuklee/tensorflow-generative-model-collections/issues/18  。   是关于在CGAN中，如果被训练样本的类别较多，是如何进行一个处理，以使最后拼接的矩阵不至于太 庞大。请问您是如何处理这个问题的呢？
谢谢您~

**Comment by TwistedW** [comment]
图像生成这一块的类别能超过20个的都算多的了。在解决标签问题我是直接把数据和标签拼接的，一般的数据集都是完全没问题的。

**Comment by li-zemin** [comment]
好的，谢谢您，那这样的话，每个样本数据后面都会加一个H*W*(cele_size)大小的三维矩阵是么？

**Comment by TwistedW** [comment]
我使用one_hot编码来指定标签的，也就是一维矩阵

**Comment by li-zemin** [comment]
好的，谢谢您~
